language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_script:
  - cd /home/ec2-user/app/step1/freelec-springboot2-webservice

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test --warning-mode=all --stacktrace"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - jelee9138@daum.net